import Head from 'next/head'
import { useReducer } from 'react'
import Button from '../components/Button'
import Display from '../components/Display'
import styles from '../styles/Home.module.css'
import * as math from 'mathjs'

const reducer = (state, action) => {
  switch (action.type) {
    case 'arg':
      return {
        ...state,
        arg: state.arg + action.payload.arg
      }
    case 'reset':
      return {
        ...state,
        arg: '',
        result: 0
      }
    case 'total':
      return {
        ...state,
        result: state.arg == '' ? 0 : math.evaluate(state.arg)
      }
    case 'minus':
      return {
        ...state,
        arg: state.arg 
      }
  }
}

export default function Home() {
  const [state, dispatch] = useReducer(reducer, {
    result: 0,
    arg: ''
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.divcont}>
          <Display result={state.result} arg={state.arg} />
          <div className={styles.buttonWrapper}>
            <Button dispatch={dispatch} state={state} />
          </div>
        </div>
      </main>
    </div>
  )
}
